services:
  app:
    build: .
    image: astronacci-app:dev
    container_name: astronacci-app
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - composer-cache:/root/.composer
      - npm-cache:/root/.npm
    ports:
      - "8000:8000"
      - "5173:5173"
    tty: true
    stdin_open: true

volumes:
  composer-cache:
  npm-cache:
